//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftManagerPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftManagerPlus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string name MyConnectionStringName was not found in the web.config or app.config file. To resolve this error, run Linquify, and in the settings dialog, provide the proper connection string name or un-checkmark the option to &apos;Use connection string specified in web.config&apos;..
        /// </summary>
        internal static string BusinessBaseType_BusinessBaseType_The_connection_string_name_MyConnectionStringName_was_not_found_in_the_web_config_or_app_config_file__To_resolve_this_error__run_Linquify__and_in_the_settings_dialog__provide_the_proper_connection_string_name_or_un_checkmark_the_option_to__Use_connection_string_specified_in_web_config__ {
            get {
                return ResourceManager.GetString(@"BusinessBaseType_BusinessBaseType_The_connection_string_name_MyConnectionStringName_was_not_found_in_the_web_config_or_app_config_file__To_resolve_this_error__run_Linquify__and_in_the_settings_dialog__provide_the_proper_connection_string_name_or_un_checkmark_the_option_to__Use_connection_string_specified_in_web_config__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lg.
        /// </summary>
        internal static string FormMinecraft_btn_UserSize_Click_Lg {
            get {
                return ResourceManager.GetString("FormMinecraft_btn_UserSize_Click_Lg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sm.
        /// </summary>
        internal static string FormMinecraft_btn_UserSize_Click_Sm {
            get {
                return ResourceManager.GetString("FormMinecraft_btn_UserSize_Click_Sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning..
        /// </summary>
        internal static string FormMinecraft_BtnDeleteUserClick_Warning_ {
            get {
                return ResourceManager.GetString("FormMinecraft_BtnDeleteUserClick_Warning_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help?.
        /// </summary>
        internal static string FormMinecraft_BtnHelpClick_Help_ {
            get {
                return ResourceManager.GetString("FormMinecraft_BtnHelpClick_Help_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a User before you can save..
        /// </summary>
        internal static string FormMinecraft_BtnSaveClick_You_must_select_a_User_before_you_can_save_ {
            get {
                return ResourceManager.GetString("FormMinecraft_BtnSaveClick_You_must_select_a_User_before_you_can_save_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured.
        /// </summary>
        internal static string FormMinecraft_FormMinecraft_Error_Occured {
            get {
                return ResourceManager.GetString("FormMinecraft_FormMinecraft_Error_Occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string FormMinecraft_LaunchMinecraft_Backup {
            get {
                return ResourceManager.GetString("FormMinecraft_LaunchMinecraft_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup save files?.
        /// </summary>
        internal static string FormMinecraft_LaunchMinecraft_Backup_save_files_ {
            get {
                return ResourceManager.GetString("FormMinecraft_LaunchMinecraft_Backup_save_files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string FormMinecraft_LaunchMinecraft_Error_ {
            get {
                return ResourceManager.GetString("FormMinecraft_LaunchMinecraft_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Minecraft Now!.
        /// </summary>
        internal static string FormMinecraft_LaunchMinecraft_Launch_Minecraft_Now_ {
            get {
                return ResourceManager.GetString("FormMinecraft_LaunchMinecraft_Launch_Minecraft_Now_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for process to end..
        /// </summary>
        internal static string FormMinecraft_LaunchMinecraft_Waiting_for_process_to_end_ {
            get {
                return ResourceManager.GetString("FormMinecraft_LaunchMinecraft_Waiting_for_process_to_end_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your first user..
        /// </summary>
        internal static string FormMinecraft_LoadUsers_Create_your_first_user_ {
            get {
                return ResourceManager.GetString("FormMinecraft_LoadUsers_Create_your_first_user_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User load error..
        /// </summary>
        internal static string FormMinecraft_LoadUsers_User_load_error_ {
            get {
                return ResourceManager.GetString("FormMinecraft_LoadUsers_User_load_error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Username is already in use..
        /// </summary>
        internal static string FormMinecraft_SaveSettings_This_Username_is_already_in_use_ {
            get {
                return ResourceManager.GetString("FormMinecraft_SaveSettings_This_Username_is_already_in_use_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Complete.
        /// </summary>
        internal static string FormMinecraft_ToolStripMenuItemBackupClick_Backup_Complete {
            get {
                return ResourceManager.GetString("FormMinecraft_ToolStripMenuItemBackupClick_Backup_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup complete. Exit?.
        /// </summary>
        internal static string FormMinecraft_ToolStripMenuItemBackupClick_Backup_complete__Exit_ {
            get {
                return ResourceManager.GetString("FormMinecraft_ToolStripMenuItemBackupClick_Backup_complete__Exit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose a Username..
        /// </summary>
        internal static string UserForm_BtnSaveClick_You_must_choose_a_Username_ {
            get {
                return ResourceManager.GetString("UserForm_BtnSaveClick_You_must_choose_a_Username_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose an Avatar..
        /// </summary>
        internal static string UserForm_BtnSaveClick_You_must_choose_an_Avatar_ {
            get {
                return ResourceManager.GetString("UserForm_BtnSaveClick_You_must_choose_an_Avatar_", resourceCulture);
            }
        }
    }
}
