//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MinecraftManagerPlus", "UserSettings", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MinecraftManagerPlus.App_Data.User), "Settings", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MinecraftManagerPlus.App_Data.Settings))]

#endregion

namespace MinecraftManagerPlus.App_Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DataModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DataModelContainer object using the connection string found in the 'DataModelContainer' section of the application configuration file.
        /// </summary>
        public DataModelContainer() : base("name=DataModelContainer", "DataModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataModelContainer object.
        /// </summary>
        public DataModelContainer(string connectionString) : base(connectionString, "DataModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataModelContainer object.
        /// </summary>
        public DataModelContainer(EntityConnection connection) : base(connection, "DataModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Settings> Settings
        {
            get
            {
                if ((_Settings == null))
                {
                    _Settings = base.CreateObjectSet<Settings>("Settings");
                }
                return _Settings;
            }
        }
        private ObjectSet<Settings> _Settings;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSettings(Settings settings)
        {
            base.AddObject("Settings", settings);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MinecraftManagerPlus", Name="Settings")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Settings : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Settings object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="optionsFile">Initial value of the OptionsFile property.</param>
        /// <param name="backupCount">Initial value of the BackupCount property.</param>
        /// <param name="optionsPath">Initial value of the OptionsPath property.</param>
        /// <param name="sharePath">Initial value of the SharePath property.</param>
        /// <param name="targetPath">Initial value of the TargetPath property.</param>
        /// <param name="workingDirectory">Initial value of the WorkingDirectory property.</param>
        /// <param name="debugging">Initial value of the Debugging property.</param>
        /// <param name="javaPath">Initial value of the JavaPath property.</param>
        /// <param name="launchWithoutJava">Initial value of the LaunchWithoutJava property.</param>
        public static Settings CreateSettings(global::System.Guid id, global::System.String optionsFile, global::System.Int32 backupCount, global::System.String optionsPath, global::System.String sharePath, global::System.String targetPath, global::System.String workingDirectory, global::System.Boolean debugging, global::System.String javaPath, global::System.Boolean launchWithoutJava)
        {
            Settings settings = new Settings();
            settings.Id = id;
            settings.OptionsFile = optionsFile;
            settings.BackupCount = backupCount;
            settings.OptionsPath = optionsPath;
            settings.SharePath = sharePath;
            settings.TargetPath = targetPath;
            settings.WorkingDirectory = workingDirectory;
            settings.Debugging = debugging;
            settings.JavaPath = javaPath;
            settings.LaunchWithoutJava = launchWithoutJava;
            return settings;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OptionsFile
        {
            get
            {
                return _OptionsFile;
            }
            set
            {
                OnOptionsFileChanging(value);
                ReportPropertyChanging("OptionsFile");
                _OptionsFile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OptionsFile");
                OnOptionsFileChanged();
            }
        }
        private global::System.String _OptionsFile;
        partial void OnOptionsFileChanging(global::System.String value);
        partial void OnOptionsFileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BackupCount
        {
            get
            {
                return _BackupCount;
            }
            set
            {
                OnBackupCountChanging(value);
                ReportPropertyChanging("BackupCount");
                _BackupCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BackupCount");
                OnBackupCountChanged();
            }
        }
        private global::System.Int32 _BackupCount;
        partial void OnBackupCountChanging(global::System.Int32 value);
        partial void OnBackupCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OptionsPath
        {
            get
            {
                return _OptionsPath;
            }
            set
            {
                OnOptionsPathChanging(value);
                ReportPropertyChanging("OptionsPath");
                _OptionsPath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OptionsPath");
                OnOptionsPathChanged();
            }
        }
        private global::System.String _OptionsPath;
        partial void OnOptionsPathChanging(global::System.String value);
        partial void OnOptionsPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SharePath
        {
            get
            {
                return _SharePath;
            }
            set
            {
                OnSharePathChanging(value);
                ReportPropertyChanging("SharePath");
                _SharePath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SharePath");
                OnSharePathChanged();
            }
        }
        private global::System.String _SharePath;
        partial void OnSharePathChanging(global::System.String value);
        partial void OnSharePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TargetPath
        {
            get
            {
                return _TargetPath;
            }
            set
            {
                OnTargetPathChanging(value);
                ReportPropertyChanging("TargetPath");
                _TargetPath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TargetPath");
                OnTargetPathChanged();
            }
        }
        private global::System.String _TargetPath;
        partial void OnTargetPathChanging(global::System.String value);
        partial void OnTargetPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WorkingDirectory
        {
            get
            {
                return _WorkingDirectory;
            }
            set
            {
                OnWorkingDirectoryChanging(value);
                ReportPropertyChanging("WorkingDirectory");
                _WorkingDirectory = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WorkingDirectory");
                OnWorkingDirectoryChanged();
            }
        }
        private global::System.String _WorkingDirectory;
        partial void OnWorkingDirectoryChanging(global::System.String value);
        partial void OnWorkingDirectoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Debugging
        {
            get
            {
                return _Debugging;
            }
            set
            {
                OnDebuggingChanging(value);
                ReportPropertyChanging("Debugging");
                _Debugging = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Debugging");
                OnDebuggingChanged();
            }
        }
        private global::System.Boolean _Debugging;
        partial void OnDebuggingChanging(global::System.Boolean value);
        partial void OnDebuggingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JavaPath
        {
            get
            {
                return _JavaPath;
            }
            set
            {
                OnJavaPathChanging(value);
                ReportPropertyChanging("JavaPath");
                _JavaPath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("JavaPath");
                OnJavaPathChanged();
            }
        }
        private global::System.String _JavaPath;
        partial void OnJavaPathChanging(global::System.String value);
        partial void OnJavaPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LaunchWithoutJava
        {
            get
            {
                return _LaunchWithoutJava;
            }
            set
            {
                OnLaunchWithoutJavaChanging(value);
                ReportPropertyChanging("LaunchWithoutJava");
                _LaunchWithoutJava = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LaunchWithoutJava");
                OnLaunchWithoutJavaChanged();
            }
        }
        private global::System.Boolean _LaunchWithoutJava;
        partial void OnLaunchWithoutJavaChanging(global::System.Boolean value);
        partial void OnLaunchWithoutJavaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MinecraftManagerPlus", "UserSettings", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MinecraftManagerPlus.UserSettings", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MinecraftManagerPlus.UserSettings", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MinecraftManagerPlus.UserSettings", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("MinecraftManagerPlus.UserSettings", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MinecraftManagerPlus", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="imageIndex">Initial value of the ImageIndex property.</param>
        public static User CreateUser(global::System.Guid id, global::System.String username, global::System.Int32 imageIndex)
        {
            User user = new User();
            user.Id = id;
            user.Username = username;
            user.ImageIndex = imageIndex;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageIndex
        {
            get
            {
                return _ImageIndex;
            }
            set
            {
                OnImageIndexChanging(value);
                ReportPropertyChanging("ImageIndex");
                _ImageIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ImageIndex");
                OnImageIndexChanged();
            }
        }
        private global::System.Int32 _ImageIndex;
        partial void OnImageIndexChanging(global::System.Int32 value);
        partial void OnImageIndexChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MinecraftManagerPlus", "UserSettings", "Settings")]
        public Settings Setting
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Settings>("MinecraftManagerPlus.UserSettings", "Settings").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Settings>("MinecraftManagerPlus.UserSettings", "Settings").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Settings> SettingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Settings>("MinecraftManagerPlus.UserSettings", "Settings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Settings>("MinecraftManagerPlus.UserSettings", "Settings", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
